# Generated by Django 4.0.2 on 2022-02-27 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisetup', '0003_consumer_otp_alter_consumer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='browser',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='city',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='local_ip',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='mac_address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='router_ip',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='state',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='station',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Work', 'Works'), ('Others', 'Others')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='publish_date'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
