# Generated by Django 4.0.2 on 2022-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisetup', '0005_alter_consumer_address_alter_consumer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(default='null@null.com', max_length=100),
        ),
    ]
